#!/bin/bash
CAT=mdcat
dirman="$HOME/.dotfiles/alisa/" 
sshman() {
$CAT $dirman/utils/ssh.md
}
tarman() {
$CAT $dirman/utils/tar.md
}
grepman() {
$CAT $dirman/utils/grep.md
}
while [ -n "$1" ]
       do
       case "$1" in
	    ssh )sshman;;
	    tar )tarman;;
	    grep )grepman;;
            -?)help;;
          esac
   shift
done
