#!/bin/bash

myhelp() {

cat << EOF 
-----------------------------------------------------
 ##   ##  ##  ##   ##  ##   ######   ##       #####   
 ### ###  ##  ##   ##  ##   ##       ##       ##  ##  
 #######  ##  ##   ##  ##   ##       ##       ##  ##  
 ## # ##   ####    ######   ####     ##       #####   
 ##   ##    ##     ##  ##   ##       ##       ##      
 ##   ##    ##     ##  ##   ##       ##       ##      
 ##   ##    ##     ##  ##   ######   ######   ##   
-----------------------------------------------------
EOF
cat << EOF 
alias yz    | yazi
alias myzsh | source ~/.zshrc
alias ll    | Comand ls -la
alias z     | Command cd ..
alias zz    | Command cd ../..
alias rmdir | Command rm -rf 
alias st    | Command systemctl
EOF 

}
